# -*- coding: utf-8 -*-
"""Copy of AEO Monitor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdD8YKJpm8YK4NUsIGG8M_w1YFz4nJQO

# AEO Monitoring Tool - Tutorial
*(Answer Engine Optimization, SEO for LLMs with web search)*

This script runs a series of questions against a series of models, and monitors for keywords in the responses and citations. This allows you to track AEO performance over time, and measure the impact of optimization efforts in social and marketing campaigns.

NOTE: This tool should be used in combination with a content and social strategy, so that new mentions and citations can be measured in real-time and charted as your campaigns build more reference material for AEO.

## Overview
- **OpenRouter**: Single interface & API Key for querying all models
- **Web Search**: Enabled with all queries so citation are included
- **Monitoring**: Detect brand name mentions, and track cited domains
- **Analytics**: Results sent to PostHog for dashboards & reports

## Requirements
- OpenRouter API Key
- PostHog API Key
"""

!pip install posthog

import asyncio
from openai import OpenAI, AsyncOpenAI
from google.colab import userdata
from posthog import Posthog

# Setup Config and Clients
config = {
    "base_url": "https://openrouter.ai/api/v1",
    "api_key": userdata.get("OPENROUTER_API_KEY")
}

client = OpenAI(**config)
async_client = AsyncOpenAI(**config)
posthog = Posthog(
    project_api_key=userdata.get("POSTHOG_API_KEY"),
    host='https://app.posthog.com'
)

keywords = ["appsmith", "appsmithai"]
domains = ["appsmith.com", "appsmithai.com"]
models = ["openai/gpt-4o", "perplexity/sonar-pro", "anthropic/claude-sonnet-4"]
prompts = [
    "What's the best open source low code tool for building apps in 2025?",
    "What's the best drag and drop app builder with SSO in 2025?"
    ]

"""## Basic Example
No concurrency, error handling, or type checking. Works, but it is SLOW! ~2.5 minutes for 3 models X 2 prompts.
"""

# UTILIZES OPENAI RESPONSES API

for model in models:
    print(f"Model: {model}")
    for prompt in prompts:
        print(f"Prompt: {prompt}")

        response = client.responses.create(
            model=f"{model}:online",
            input=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            stream=False,
            reasoning={"effort": "medium"}  # optional; for reasoning models
        )

        content = response.output[0].content[0].text.lower()

        for keyword in keywords:
            if keyword in content:
                print(f"--MatchType: Keyword, Model: {model}, Prompt: {prompt}, Mentions: {content.count(keyword)}")
                break

        annotations = getattr(response.output[0].content[0], "annotations", [])
        print(f"{len(annotations)} annotations returned")

        for annotation in annotations:
            url = annotation.url.lower()
            print(f"URL: {url}")
            for domain in domains:
                if domain in url:
                    print(f"--MatchType: Domain, Model: {model}, Prompt: {prompt}")
                    break

'''
THIS UTILIZES OPENAI CHAT COMPLETIONS API
for model in models:
  print(f"Model: {model}")
  for prompt in prompts:
    print(f"Prompt: {prompt}")
    completion = client.chat.completions.create(
      model=f"{model}:online",
      stream=False,
      messages=[
        {
          "role": "user",
          "content": prompt
        }
      ]
    )
    content = completion.choices[0].message.content.lower()
    for keyword in keywords:
      if keyword in content:
        print(f"--MatchType: Keyword, Model: {model}, Prompt: {prompt}, Mentions: {content.count(keyword)}")
        break

    annotations = completion.choices[0].message.annotations
    print(f"{len(annotations)} annotations returned")
    for annotation in annotations:
      url = annotation.url_citation.url.lower()
      print(f"URL: {url}")
      for domain in domains:
        if domain in url:
          print(f"--MatchType: Domain, Model: {model}, Prompt: {prompt}")
          break'''

"""### Example Output

## ToDo and Feature Ideas
- OpenAI is returning only 5 citations by default. Need to pass extra model-specific param to get more results. Maybe limit all models to 10?
- Match detection is regex based, and doesn't take into account ratio to mentions of other brands, where our mentions may be secondary. LLM review could extract top brand in each response.
- Run in GitHub Actions or Railway on cron job, then schedule reports in PostHog

## Notes
- The (keywords + domains + prompts + models) combo should be consistent, and logged over time to monitor for changes in responses. If any input is changed, those responses should be grouped and reported as separate experiments, using a different event ID in PostHog.
"""